import { createFileRoute } from '@tanstack/react-router';
import { useState } from 'react';
import { ArrowUpRight, ArrowRight, Activity, Heart, ShieldCheck, Accessibility, Leaf, Stethoscope, Sparkles, Smile, Meh, Frown, Sun, Cloud, Check, LockKeyhole, Menu } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import heroImage from '@/assets/wellbeing-hero.jpg';

export const Route = createFileRoute('/')({
 head: () => ({ meta: [{ title: 'Vita — Health & Human Wellbeing' }, { name: 'description', content: 'Make room for a healthier you. Explore accessible care, preventive health, and everyday wellbeing with Vita.' }, { property: 'og:title', content: 'Vita — Health & Human Wellbeing' }, { property: 'og:description', content: 'A more human approach to health. Care, prevention, and wellness in one place.' }, { property: 'og:type', content: 'website' }, { name: 'twitter:card', content: 'summary_large_image' }] }),
 component: Index,
});
const services = [
 { title: 'Find your care', description: 'A little guidance. The right support. Explore care that meets you where you are.', tag: 'Medical assistance', icon: Stethoscope, color: 'text-primary', detail: 'Choose the support you need', options: ['General health concerns', 'Mental health support', 'Help preparing for a doctor visit'], advice: ['Write down your symptoms, when they started, and any medications you take. A qualified clinician can help assess your next steps.', 'Consider speaking with a licensed mental health professional or someone you trust. If you are in immediate danger, contact your local emergency service.', 'Bring your medication list, relevant medical history, and three questions you want answered. Ask about follow-up care before you leave.'] },
 { title: 'Stay a step ahead', description: 'Small actions today. A healthier tomorrow. Make prevention part of your routine.', tag: 'Preventive care', icon: ShieldCheck, color: 'text-sky', detail: 'Your prevention checklist', options: ['Routine health checkups', 'Sleep and recovery', 'Everyday movement'], advice: ['Ask your clinician which screenings and vaccinations are appropriate for your age, medical history, and location.', 'Try a consistent bedtime, a quiet sleeping space, and time away from screens before bed. Discuss ongoing sleep issues with a clinician.', 'Start with movement that feels comfortable for you. Adapt activities to your abilities and ask your clinician if you have health concerns.'] },
 { title: 'Feel more like you', description: 'Find your balance with mindful moments and everyday wellness habits.', tag: 'Mind & body', icon: Leaf, color: 'text-coral', detail: 'A moment for yourself', options: ['Guided breathing', 'A mindful pause', 'Build a daily ritual'], advice: ['Breathe gently at a comfortable pace. Stop if you feel dizzy or uncomfortable.', 'Notice five things you can see, four you can feel, and three you can hear. Take a moment without judging how you feel.', 'Choose one small habit: a morning stretch, a glass of water, or a quiet minute. Start small and let it grow.'] },
 { title: 'Health for everyone', description: 'Different needs. Equal possibilities. A more accessible path to better health.', tag: 'Inclusive health', icon: Accessibility, color: 'text-primary', detail: 'Care without barriers', options: ['Larger reading text', 'Prepare for accessible care', 'Support for a caregiver'], advice: ['Larger reading text is now enabled on this page.', 'Ask your care provider about step-free access, interpreters, accessible equipment, and communication accommodations before your appointment.', 'Prepare a shared list of care needs and questions, with the person’s consent. Make time for your own rest and support too.'] },
];
const moods = [{label:'Amazing',icon:Sun},{label:'Good',icon:Smile},{label:'Okay',icon:Meh},{label:'Low',icon:Cloud},{label:'Not great',icon:Frown}];
function Index(){
 const [selected,setSelected]=useState<number|null>(null);const [choice,setChoice]=useState<number|null>(null);const [mood,setMood]=useState('');const [started,setStarted]=useState(false);const [breathing,setBreathing]=useState(false);const [largeText,setLargeText]=useState(false);const [mobileMenu,setMobileMenu]=useState(false);
 const current=selected===null?null:services[selected];
 const open=(n:number)=>{setSelected(n);setChoice(null);setBreathing(false)};
 const explore=()=>document.getElementById('care-options')?.scrollIntoView({behavior:'smooth'});
 return <div className={largeText?'accessible-text':''}>
 <a href="#main" className="sr-only focus:not-sr-only">Skip to content</a>
 <div className="page-wrap">
 <header className="site-header"><a className="logo" href="/" aria-label="Vita home"><Activity className="logo-mark" strokeWidth={2.8}/>vita<span className="text-primary">.</span></a>
 <nav className="nav-links" aria-label="Main navigation"><Button variant="ghost" className="nav-item" data-active="true" onClick={explore}>Discover</Button><Button variant="ghost" className="nav-item" onClick={()=>open(0)}>Healthcare</Button><Button variant="ghost" className="nav-item" onClick={()=>open(2)}>Wellness</Button><Button variant="ghost" className="nav-item" onClick={()=>open(3)}>Accessibility</Button></nav>
 <div className="flex items-center gap-2"><Button variant="outline" onClick={()=>setStarted(true)}>My wellbeing <ArrowUpRight/></Button><Button variant="ghost" size="icon" className="md:hidden" aria-label="Open navigation" onClick={()=>setMobileMenu(!mobileMenu)}><Menu/></Button></div></header>
 {mobileMenu&&<nav className="flex flex-wrap gap-2 pb-4" aria-label="Mobile navigation">{services.map((s,i)=><Button key={s.title} variant="ghost" onClick={()=>{open(i);setMobileMenu(false)}}>{s.title}</Button>)}</nav>}
 <main id="main"><section className="hero"><img className="hero-image" src={heroImage} alt="Woman enjoying a morning run along a sunlit coastal trail" width={1920} height={1024}/><div className="hero-content"><div className="eyebrow text-primary"><span className="h-1.5 w-1.5 rounded-full bg-primary"/> A more human approach to health</div><h1>Your health.<br/>Your pace.<br/><span className="text-primary">Your possibilities.</span></h1><p className="hero-copy">Better care. Small daily steps. A little more balance.<br/>A healthier you starts right where you are.</p><Button size="lg" className="mt-7 h-12 px-6" onClick={explore}>Explore your wellbeing <ArrowUpRight/></Button><div className="hero-foot"><div className="flex -space-x-2">{['A','M','J'].map((v,i)=><span key={v} className={`flex h-7 w-7 items-center justify-center rounded-full border-2 border-background bg-secondary text-xs ${i===1?'text-coral':'text-sky'}`}>{v}</span>)}</div><span>For every body. And every chapter.</span></div></div><div className="hero-label"><Leaf size={14}/> Live well. Feel better.</div></section>
 <div className="assurance"><span><ShieldCheck/> Care with you at the center</span><span><Accessibility/> Designed for every ability</span><span><LockKeyhole/> Your check-in stays on this page</span><span><Heart/> Science-minded. Human-first.</span></div>
 <section id="care-options"><div className="section-heading"><div><div className="eyebrow text-primary">Your wellbeing, connected</div><h2>A little support. A lot of possibility.</h2><p>Whatever you need today, there’s a place to start.</p></div><span className="hidden sm:flex items-center gap-2 text-xs text-muted-foreground">Made for real life <Sparkles size={14}/></span></div><div className="service-grid">{services.map((s,i)=><article className="service-card" key={s.title}><div className={`service-icon ${s.color}`}><s.icon/></div><h3>{s.title}</h3><p>{s.description}</p><div className="card-bottom"><span>{s.tag}</span><Button size="icon" variant="ghost" aria-label={`Explore ${s.title.toLowerCase()}`} onClick={()=>open(i)}><ArrowUpRight/></Button></div></article>)}</div></section>
 <section><div className="section-heading"><div><div className="eyebrow text-primary">Small steps, real progress</div><h2>Make a little room for you.</h2></div><span className="text-xs text-muted-foreground">Your daily reset</span></div><div className="daily-grid"><div className="daily-panel"><h3>How are you feeling today?</h3><p className="text-sm text-muted-foreground">Every feeling is a good place to start.</p><div className="mood-row">{moods.map(m=><Button key={m.label} variant={mood===m.label?'default':'secondary'} className="mood-button" aria-pressed={mood===m.label} onClick={()=>setMood(m.label)}><m.icon/>{m.label}</Button>)}</div><p aria-live="polite" className="text-xs text-muted-foreground">{mood?`You checked in as “${mood}”. ${mood==='Low'||mood==='Not great'?'Be kind to yourself. A quiet moment or reaching out can help.':'Thank you for taking a moment for yourself.'}`:'A moment to check in. No right or wrong answers.'}</p></div><div className="daily-panel"><div className="flex items-center justify-between"><h3>Your feel-good essentials</h3><Leaf className="text-primary" size={19}/></div>{[['Take a movement break','Mindful movement'],['Make time for a glass of water','Stay refreshed'],['Pause for a deep breath','One quiet moment']].map(([label,tag])=><div className="habit-row" key={label}><label><input type="checkbox"/>{label}</label><span className="hidden sm:inline">{tag}</span></div>)}</div></div></section></main>
 <footer><span className="flex items-center gap-2"><Activity size={16} className="text-primary"/> vita. <span>Healthier humans. Brighter possibilities.</span></span><span>Wellbeing guidance, not medical advice. In an emergency, call your local emergency number.</span></footer></div>
 <Dialog open={current!==null} onOpenChange={v=>{if(!v)setSelected(null)}}><DialogContent><DialogTitle>{current?.detail}</DialogTitle><DialogDescription>{current?.description}</DialogDescription><div className="flex flex-col gap-2 py-3">{current?.options.map((o,i)=><Button key={o} variant={choice===i?'default':'outline'} className="justify-between h-12" onClick={()=>{setChoice(i);if(selected===3&&i===0)setLargeText(true)}}>{o}<ArrowRight/></Button>)}</div>{choice!==null&&current&&<div aria-live="polite" className="border-t pt-4"><p className="text-sm leading-7 text-muted-foreground">{current.advice[choice]}</p>{selected===2&&choice===0&&<><div className={`breath-orbit ${breathing?'running':''}`}>{breathing?'Breathe gently':'A quiet moment'}</div><Button className="w-full" onClick={()=>setBreathing(!breathing)}>{breathing?'Finish breathing':'Start breathing'}</Button></>}</div>}<p className="text-xs text-muted-foreground">General wellbeing information only. A qualified professional can advise on your personal health needs.</p></DialogContent></Dialog>
 <Dialog open={started} onOpenChange={setStarted}><DialogContent><DialogTitle>Your wellbeing starts with you.</DialogTitle><DialogDescription>What would you like to focus on today?</DialogDescription><div className="grid gap-3 py-4">{services.map((s,i)=><Button key={s.title} variant="outline" className="h-12 justify-between" onClick={()=>{setStarted(false);open(i)}}><span className="flex items-center gap-3"><s.icon className={s.color}/>{s.title}</span><ArrowUpRight/></Button>)}</div><p className="flex gap-2 text-xs text-muted-foreground"><Check size={14}/> No account needed. Just a small step for yourself.</p></DialogContent></Dialog>
 </div>
}
